(* :Context: mGRG`mPerm` *)
(* :Author: Park, Dal-Ho *)
(* :Summary: Manipulating signed permutations *)
(* :Package Version: 2025.12 *)
(* :Mathematica Version: 9.0+ *)

BeginPackage["mGRG`mPerm`"]

(******* Usage messages for the exported symbols and functions ******)

(***** MODE 0 *****)
PermMax::usage = "PermMax[perm] gives the largest element moved by the permutation 'perm', which can be in CyclesPhased, Imag, or GenSet form."
ToImag::usage  = "ToImag[cperm] converts a CyclesPhased permutation 'cperm' into its Imag (image list) representation. ToImag[cperm, len] pads the list to the specified length 'len'."
ToCycl::usage  = "ToCycl[iperm] converts an Imag permutation 'iperm' or a standard permutation list into its CyclesPhased form {Cycles[...], sign}."

(* Heads *)
Imag::usage   = "Imag[n1, n2, ...] is a head representing a permutation by its image list (the result of PermutationList)."
GenSet::usage = "GenSet[p1, p2, ...] represents a set of generators for a permutation group."

(***** Mathematica Mode *****)
InversePerm::usage   = "InversePerm[perm] returns the inverse of the specified permutation."
MakePermGroup::usage = "MakePermGroup[gs, len] constructs a PermutationGroup object from a GenSet 'gs' acting on 'len' elements. It returns all elements of the group."
Orbits::usage        = "Orbits[pts, gs, len] finds the orbits of the points 'pts' under the action of the group generated by GenSet 'gs'."
PermMemberQ::usage   = "PermMemberQ[perm, len, gs] checks if a permutation 'perm' is a member of the group generated by GenSet 'gs'."
PermuteList::usage   = "PermuteList[list, perm] permutes the 'list' according to the permutation 'perm'."

(********************************************************************)
Begin["`Private`"]

(* 'PermutationList' 함수의 동작이 버전 9에서 바뀜 *)
If [System`$VersionNumber < 9.0, Throw @ Message[General::version, "9.0", $VersionNumber]]

(********************************************************************)
(************************* Mathematica Mode *************************)
(********************************************************************)
(*
    CyclesPhased: {Cycles[{...}], s}, where Abs[s] == 1
*)

(*** Type Checking and Error Messages ***)
ToCycl::badsgn   = "The coefficient `1` in `2` must have an absolute value of 1."
PermMemberQ::len = "The specified length `1` is too small for the given permutations."

(* CyclesPhased? *)
permCyclesQ[{cycl_Cycles, s_}] := PermutationCyclesQ[cycl] /; Abs[s] == 1
permCyclesQ[___]               := False

(* is a set of CyclesPhased, with the head GenSet? *)
gensetQ[GenSet[___?permCyclesQ]] := True
gensetQ[___]                     := False

(****************************** Core Logic **************************)

(* Remove identity permutations from a generator set *)
GenSet[pre___, {Cycles[{}], 1}, post___] := GenSet[pre, post]

(* Find the largest point moved by a permutation *)
PermMax[{cycl_Cycles, _}]  := PermutationMax[cycl]
PermMax[s_. * Imag[ns___]] := Length[{ns}]
PermMax[g_GenSet?gensetQ]  := Max[0, PermMax /@ List @@ g]

(* Convert from Imag or List form to CyclesPhased {Cycles[...], sign} form *)
ToCycl[s_  * Imag[ns___]] := (Message[ToCycl::badsgn, s, s*Imag[ns]]; $Failed) /; Abs[s] =!= 1
ToCycl[s_. * Imag[ns___]] := {PermutationCycles[{ns}], s}
ToCycl[imagL_List]        := {PermutationCycles[imagL], 1}

(* Convert from CyclesPhased to Imag form *)
ToImag[perm_?permCyclesQ]              := ToImag[perm, PermMax[perm]]
ToImag[{cycl_Cycles, s_}, len_Integer] := s * Imag @@ PermutationList[cycl, len]

(* Convert from Cycles in List form to Imag form *)
ToImag[cyclL_List, len_Integer] := Imag @@ PermutationList[Cycles @ cyclL, len]
ToImag[0,         _]            := 0  (* CanonicalPerm의 적절한 동작에 필요 *)

(*
    CyclesSigned: {Cycles[{...}], +1|-1}
*)

(* Inverse of a permutation *)
InversePerm[x_?NumericQ * perm_] := 1/x InversePerm[perm]
InversePerm[perm_?permCyclesQ]   := {InversePermutation[First[perm]], 1/Last[perm]}
InversePerm[Imag[ns___]]         := Imag @@ Ordering[{ns}]

(* Permute a list *)
PermuteList[argL_List, {cycl_Cycles, _}] := Permute[argL, cycl]
PermuteList[argL_List, s_. * imag_Imag]  := PermuteList[argL, List @@ imag]
PermuteList[argL_List, imagL_List]       := argL[[ Ordering[imagL] ]]  (* an efficient implementation *)

(********************** Group Theory Functions **********************)

(* Construct a PermutationGroup from a GenSet *)
MakePermGroup[GenSet[], ___]            := {}
MakePermGroup[gs_GenSet]                := MakePermGroup[gs, PermMax @ gs]
MakePermGroup[gs_?gensetQ, len_Integer] := toCyclesSigned[#, len]& /@ GroupElements[gensetToPermGroup[gs, len]]

(* Find orbits of points under the group action *)
Orbits[pts_List, gs_?gensetQ, len_Integer] := GroupOrbits[gensetToPermGroup[gs, len], pts]

(* Check for group membership *)
PermMemberQ[perm_?permCyclesQ, len_Integer, gs_?gensetQ] := (Message[PermMemberQ::len, len]; False) /; len < PermMax[perm] || len < PermMax[gs]
PermMemberQ[perm_?permCyclesQ, len_Integer, gs_?gensetQ] := GroupElementQ[gensetToPermGroup[gs, len], toCyclesProper[perm, len]]
PermMemberQ[s_. * imag_Imag,   len_Integer, gs_GenSet]   := PermMemberQ[ToCycl[s*imag], len, gs]

(***** Internal helper functions *****)

(* Convert a GenSet into a standard PermutationGroup object for internal calculations *)
gensetToPermGroup[GenSet[scycl___], len_Integer] := PermutationGroup[toCyclesProper[#, len]& /@ {scycl}]

(* A signed permutation in S_n is embedded into a standard permutation in S_{n+2}.
   - A positive permutation p -> p
   - A negative permutation p -> p . (n+1, n+2)
   The sign is recovered by checking if n+1 is a fixed point. This is a very efficient trick. *)
toCyclesProper[{Cycles[cycl_],  1}, _]           := Cycles[cycl]
toCyclesProper[{Cycles[cycl_], -1}, len_Integer] := Cycles[Append[cycl, {len + 1, len + 2}]]

(* Map from a standard permutation in S_{n+2} back to a signed permutation in S_n *)
toCyclesSigned[Cycles[cycl_], len_Integer] := Module[{sign = 1, realCycles},
    realCycles = DeleteCases[cycl, {___, len + 1, ___} | {___, len + 2, ___}, Infinity];
    If [PermutationReplace[len + 1, Cycles[cycl]] =!= len + 1, sign = -1];
    {Cycles @ realCycles, sign}
]

(********************************************************************)
End[] (* end the private context *)

EndPackage[] (* end the package context *)
