(********************************************************************)
(************************* xPermCustom Mode *************************)
(********************************************************************)

(* Yields the image of point p under a perm *)
OnPoints[lst_List,  perm_] := OnPoints[#, perm]& /@ lst  (* Listable *)

(* In MMA, PermutationReplace[p, Cycles[{...}] *)
OnPoints[p_Integer, {Cycles[{___List, {___, p_, q_, ___}, ___List}], _}] := q
OnPoints[p_Integer, {Cycles[{___List, {q_, ___, p_},      ___List}], _}] := q
OnPoints[p_Integer, {Cycles[{___List}], _}]                              := p

OnPoints[p_Integer, s_. * perm_Imag]         := OnPoints[p, perm]  (* 부호 무시 *)
OnPoints[p_Integer, imag:Imag[___, p_, ___]] := imag[[p]]
OnPoints[p_Integer, Imag[___]]               := p

(* Gives the CyclesSigned permutation that converts lst1 into lst2. *)
PermFromTo::diff = "`1` and `2` contain different points."
PermFromTo[lst1:head_[___], lst2:head_[___]] :=
    If [Sort[lst1] =!= Sort[lst2], Message[PermFromTo::diff, lst1, lst2],
    (* else *)                     {FindPermutation[lst1, lst2], 1}]

(* Generates a strong generating set for the group generated by GS of CyclesSigned *)
SchreierSims[gs_GenSet, opts___Rule] :=  (* One possible option is GroupActionBase -> base_List *)
    With[{len = PermMax[gs]},
        With[{chainL = GroupStabilizerChain[gensetToPermGroup[gs, len], opts]},
            With[{base = Select[chainL[[-1,1]], (# <= len)&]},  (* 부호 고려 *)
                StrongGenSet[base, GenSet @@ (toCyclesSigned[#, len]& /@ chainL[[1,-1,1]])]
            ]
        ]
    ]

(* Gives a canonical representative of the double coset S.perm.D,
   where S is generated by GS and D is the group of symmetries of the DummySets. *)
CanonicalPerm::sign = "`1` is not a sign."
Options[CanonicalPerm] = {Verbose -> False}
CanonicalPerm[perm:{_Cycles, 1 | -1}, len_, gs_GenSet, frees_List, sets:{(_DummySet | _RepeatedSet)...}, opts___Rule] := linkCanonicalPerm[perm, len, SchreierSims[gs], frees, sets, opts]
CanonicalPerm[s_. * imag_Imag,        len_, gs_GenSet, frees_List, sets:{(_DummySet | _RepeatedSet)...}, opts___Rule] := (
        If [s^2 =!= 1, Message[CanonicalPerm::sign, s]; Return[$Failed]];

        With[{result = CanonicalPerm[ToCycl[s * imag], len, gs, frees, sets, opts]},
            If [result =!= Null, ToImag[result, len],
            (* else *)           Null]  (* MathLink error in xpermConnect[] *)
        ]
    )

(********************************************)

$MyDevDirectory =
    With [{version = System`$Version},
        Which [
            StringMatchQ[version, "*Windows*"], "c:/Dropbox/mma",
            StringMatchQ[version, "*Linux*"],   "/home/dhpark/Dropbox/mma",
            StringMatchQ[version, "*Mac*"],     "/Users/dhpark/Dropbox/mma"
        ]
    ]

$MainDirectory :=
    With[{lst = FileNames["mGRG",
                          Join[{$MyDevDirectory},
                               StringJoin[#, "/Repository"]& /@ {$UserBasePacletsDirectory,
                                                                 $BasePacletsDirectory}]]},
        If[lst =!= {}, First[lst], {}]
    ]

xpermConnect[] :=
    If [$xpermCPP =!= True,  (* True if the connection was successful, or False if it failed. *)
        With[{version = System`$Version, dir = StringJoin[$MainDirectory, "/LibraryResources/"]},
            Module[{result = True},
                Which [
                    StringMatchQ[version, ___ ~~ "Windows" ~~ ___], $xpermExecutable = StringJoin[dir, "xPermCPP64.mswin-x86"],
                    StringMatchQ[version, ___ ~~ "Linux"   ~~ ___], $xpermExecutable = StringJoin[dir, "xPermCPP64.linux-x86"],
                    StringMatchQ[version, ___ ~~ "Mac"     ~~ ___], $xpermExecutable = StringJoin[dir, "xPermCPP64.mac-arm"],
                    True,                                           Print["Unsupported system."]; result = False
                ];

                Check[Install[$xpermExecutable], result = False];
                If [!result, Print["Connection failed."]];
                $xpermCPP = result;
                Return[result]
            ]
        ]
    ]

(* CyclesSigned -> Imag -> Unsigned imag-list *)
toImagList[gs_GenSet, len_] := Flatten @ Apply[List, toImagList[#, len]& /@ gs]
toImagList[perm_, len_]     := toImagListProper[ToImag[perm, len], len]

    (* Imag -> Unsigned imag-list *)
    toImagListProper[s_. * Imag[ns___], len_] := If [s < 0, Join[{ns}, len + {2,1}],
                                                 (* else *) Join[{ns}, len + {1,2}]]

(* Unsigned imag-list -> CyclesSigned *)
fromImagList[{(0)..},    _]          := 0  (* for CanonicalPerm *)
fromImagList[imag_List, len_Integer] := {PermutationCycles @ Drop[imag, -2],
                                         If [OnPoints[len+1, Imag @@ imag] === len+1, 1, -1]}

linkCanonicalPerm[perm_, len_Integer, sgs_, frees_List, sets_, opts___] :=
    With[{vb = Verbose /. {opts} /. Options[CanonicalPerm], callF = mGRG`mPerm`Private`MLCanonicalPerm},
        If [vb,
            Print["Calling 'MLCanonicalPerm' with the following arguments:"];
            Print["1st: perm = ", toImagList[perm, len]];
            Print["2nd: deg = ", len + 2];
            Print["3rd: {base, GS} = ", List @ sgsList[sgs, len]];
            Print["4th: freeps = ", frees];
            Print["5th: vds, dummies, mQ, vrs, repes = ", List @ translateSet[sets]];
        ];

        If [xpermConnect[] =!= False,
            fromImagList[
                callF[
                    toImagList[perm, len],
                    len + 2,
                    sgsList[sgs, len],
                    frees,
                    translateSet[sets]
                ],
                len
            ],
        (* else *)
            Null  (* MathLink error in xpermConnect[] *)
        ]
    ]

    sgsList[StrongGenSet[base_List, gs_GenSet], len_] := Sequence[takeNext[base, {}, Range[len]],
                                                                  toImagList[gs, len]]

        takeNext[{a_, other___}, {found___}, lst_List] :=
            With[{sublist = Complement[Select[lst, # < a&], {other}]},
                takeNext[{other}, Flatten[{found, sublist, a}], Complement[lst, sublist, {a}]]
            ]
        takeNext[{}, found_, lst_List] := Join[found, lst]

    (* translate the DummySet and RepeatedSet structures into lists of numbers: *)
    translateSet[DummySet[_, dums_, sym_]] := {Flatten[{dums}], sym}
    translateSet[RepeatedSet[lst_]]        := Flatten[{lst}]
    translateSet[sets_List]                :=
        translateSetStructure[{transpose[translateSet /@ Cases[sets, DummySet[_,{__},_]]],
                               translateSet /@ Cases[sets, _RepeatedSet]}]

        translateSetStructure[{{dumSets_, mQ_}, repSets_}] :=
            Sequence[Length /@ dumSets, Flatten[dumSets], mQ, Length /@ repSets, Flatten[repSets]]

        transpose[{}] := {{}, {}}
        transpose[x_] := Transpose[x]

linkMakePermGroup[gs_GenSet, len_Integer] := (
        If [xpermConnect[] =!= False,
            With[{result = mGRG`mPerm`Private`MLMakePermGroup[toImagList[gs, len], len+2]},
                fromImagList[#, len]& /@ Partition[result, len + 2]
            ],
        (* else *)
            Null  (* MathLink error in xpermConnect[] *)
        ]
    )
