(* :Title: mPerm.m *)
(* :Context: mPerm` *)
(* :Author: Park, Dal-Ho *)
(* :Summary: Manipulating signed permutations *)
(* :Package Version: 2025.12 *)
(* :Mathematica Version: 9.0+ *)

BeginPackage["mPerm`"]

(******* Usage messages for the exported symbols and functions ******)

(***** MODE 0 *****)
PermMax::usage = "PermMax[perm] gives the largest element moved by the permutation 'perm', which can be in CyclesPhased, Imag, or GenSet form."
ToImag::usage  = "ToImag[cperm] converts a CyclesPhased permutation 'cperm' into its Imag (image list) representation. ToImag[cperm, len] pads the list to the specified length 'len'."
ToCycl::usage  = "ToCycl[iperm] converts an Imag permutation 'iperm' or a standard permutation list into its CyclesPhased form {Cycles[...], sign}."

(* Heads *)
Imag::usage   = "Imag[n1, n2, ...] is a head representing a permutation by its image list (the result of PermutationList)."
GenSet::usage = "GenSet[p1, p2, ...] represents a set of generators for a permutation group."

(***** MODE 1 *****)
InversePerm::usage   = "InversePerm[perm] returns the inverse of the specified permutation."
MakePermGroup::usage = "MakePermGroup[gs, len] constructs a PermutationGroup object from a GenSet 'gs' acting on 'len' elements. It returns all elements of the group."
Orbits::usage        = "Orbits[pts, gs, len] finds the orbits of the points 'pts' under the action of the group generated by GenSet 'gs'."
PermMemberQ::usage   = "PermMemberQ[perm, len, gs] checks if a permutation 'perm' is a member of the group generated by GenSet 'gs'."
PermuteList::usage   = "PermuteList[list, perm] permutes the 'list' according to the permutation 'perm'."

MMALink::usage = "MMALink is an option for permutation group functions. If set to True, it attempts to use a compiled C++ backend for improved performance."

(***** MODE 2 *****)
CanonicalPerm::usage = "CanonicalPerm[perm, len, sgs, freeps, sets] gives a canonical representative of the permutation 'perm' of length 'len'. The canonicalization is performed within the double coset defined by the symmetry group 'sgs' (a StrongGenSet) and the dummy/repeated index sets 'sets'. 'freeps' is a list of free indices."
OnPoints::usage      = "OnPoints[point, perm] gives the image of a 'point' under the action of the permutation 'perm'. OnPoints[{p1, p2, ...}, perm] gives the list of images."
PermFromTo::usage    = "PermFromTo[list1, list2] gives the permutation that transforms list1 into list2."
SchreierSims::usage  = "SchreierSims[gs] computes a stabilizer chain for the group generated by the GenSet 'gs', returning a StrongGenSet object."

DummySet::usage     = "DummySet[kind, {{d1,u1},...}, sym] is a head representing a set of dummy indices of a given 'kind'. 'sym' indicates the metric symmetry (+1 for symmetric, -1 for antisymmetric, 0 for none)."
RepeatedSet::usage  = "RepeatedSet[{p1, p2, ...}] is a head representing a set of repeated indices found at positions p1, p2, etc."
StrongGenSet::usage = "StrongGenSet[base, gs] is a head representing a stabilizer chain, containing a base and a strong generating set 'gs'."

(********************************************************************)
Begin["`Private`"]

(* Version Check *) (* 'PermutationList' 함수의 동작이 버전 9에서 바뀜 *)
If [System`$VersionNumber < 9.0, Throw @ Message[General::version, "9.0", $VersionNumber]]

(********************************************************************)
(****************************** MODE 0 ******************************)
(********************************************************************)
(*
    CyclesPhased: {Cycles[{...}], s}, where Abs[s] == 1
*)

(*** Type Checking and Error Messages ***)
ToCycl::badsgn   = "The coefficient `1` in `2` must have an absolute value of 1."
PermMemberQ::len = "The specified length `1` is too small for the given permutations."

(* CyclesPhased? *)
permCyclesQ[{cycl_Cycles, s_}] := PermutationCyclesQ[cycl] /; Abs[s] == 1
permCyclesQ[___]               := False

(* a set of CyclesPhased, with the head GenSet? *)
gensetQ[GenSet[___?permCyclesQ]] := True
gensetQ[___]                     := False

(****************************** Core Logic **************************)

(* Remove identity permutations from a generator set *)
GenSet[pre___, {Cycles[{}], 1}, post___] := GenSet[pre, post]

(* Find the largest point moved by a permutation *)
PermMax[{cycl_Cycles, _}]  := PermutationMax[cycl]
PermMax[s_. * Imag[ns___]] := Length[{ns}]
PermMax[g_GenSet?gensetQ]  := Max[0, PermMax /@ List @@ g]

(* Convert from Imag or List form to CyclesPhased {Cycles[...], sign} form *)
ToCycl[s_  * Imag[ns___]] := (Message[ToCycl::badsgn, s, s*Imag[ns]]; $Failed) /; Abs[s] =!= 1
ToCycl[s_. * Imag[ns___]] := {PermutationCycles[{ns}], s}
ToCycl[imagL_List]        := {PermutationCycles[imagL], 1}

(* Convert from CyclesPhased to Imag form *)
ToImag[perm_?permCyclesQ]              := ToImag[perm, PermMax[perm]]
ToImag[{cycl_Cycles, s_}, len_Integer] := s * Imag @@ PermutationList[cycl, len]

(* Convert from Cycles in List form to Imag form *)
ToImag[cyclL_List, len_Integer] := Imag @@ PermutationList[Cycles @ cyclL, len]
ToImag[0,         _]            := 0  (* CanonicalPerm의 적절한 동작에 필요 *)

(********************************************************************)
(****************************** MODE 1 ******************************)
(********************************************************************)
(*
    CyclesSigned: {Cycles[{...}], +1|-1}
*)

(* Inverse of a permutation *)
InversePerm[x_?NumericQ * perm_] := 1/x InversePerm[perm]
InversePerm[perm_?permCyclesQ]   := {InversePermutation[First[perm]], 1/Last[perm]}
InversePerm[Imag[ns___]]         := Imag @@ Ordering[{ns}]

(* Permute a list *)
PermuteList[argL_List, {cycl_Cycles, _}] := Permute[argL, cycl]
PermuteList[argL_List, s_. * imag_Imag]  := PermuteList[argL, List @@ imag]
PermuteList[argL_List, imagL_List]       := argL[[ Ordering[imagL] ]]  (* an efficient implementation *)

(********************** Group Theory Functions **********************)

(* Construct a PermutationGroup from a GenSet *)
Options[MakePermGroup] = {MMALink -> False}
MakePermGroup[GenSet[], ___]                         := {}
MakePermGroup[gs_GenSet, opts___Rule]                := MakePermGroup[gs, PermMax @ gs, opts]
MakePermGroup[gs_?gensetQ, len_Integer, opts___Rule] :=
    If [MMALink /. {opts} /. Options[MakePermGroup], linkMakePermGroup[gs, len],                                           (* MMALink mode *)
    (* else *)                                       toCyclesSigned[#, len]& /@ GroupElements[gensetToPermGroup[gs, len]]] (* Math mode *)

(* Find orbits of points under the group action *)
Orbits[pts_List, gs_?gensetQ, len_Integer] := GroupOrbits[gensetToPermGroup[gs, len], pts]

(* Check for group membership *)
PermMemberQ[perm_?permCyclesQ, len_Integer, gs_?gensetQ] := (Message[PermMemberQ::len, len]; False) /; len < PermMax[perm] || len < PermMax[gs]
PermMemberQ[perm_?permCyclesQ, len_Integer, gs_?gensetQ] := GroupElementQ[gensetToPermGroup[gs, len], toCyclesProper[perm, len]]
PermMemberQ[s_. * imag_Imag,   len_Integer, gs_GenSet]   := PermMemberQ[ToCycl[s*imag], len, gs]

(***** Internal helper functions *****)

(* Convert a GenSet into a standard PermutationGroup object for internal calculations *)
gensetToPermGroup[GenSet[scycl___], len_Integer] := PermutationGroup[toCyclesProper[#, len]& /@ {scycl}]

(* A signed permutation in S_n is embedded into a standard permutation in S_{n+2}.
   - A positive permutation p -> p
   - A negative permutation p -> p . (n+1, n+2)
   The sign is recovered by checking if n+1 is a fixed point. This is a very efficient trick. *)
toCyclesProper[{Cycles[cycl_],  1}, _]           := Cycles[cycl]
toCyclesProper[{Cycles[cycl_], -1}, len_Integer] := Cycles[Append[cycl, {len + 1, len + 2}]]

(* Map from a standard permutation in S_{n+2} back to a signed permutation in S_n *)
toCyclesSigned[Cycles[cycl_], len_Integer] := Module[{sign = 1, realCycles},
    realCycles = DeleteCases[cycl, {___, len + 1, ___} | {___, len + 2, ___}, Infinity];
    If [PermutationReplace[len + 1, Cycles[cycl]] =!= len + 1, sign = -1];
    {Cycles @ realCycles, sign}
]

(********************************************************************)
(****************************** MODE 2 ******************************)
(********************************************************************)

(* Yields the image of point p under a perm *)
OnPoints[lst_List,  perm_] := OnPoints[#, perm]& /@ lst  (* Listable *)

(* In MMA, PermutationReplace[p, Cycles[{...}] *)
OnPoints[p_Integer, {Cycles[{___List, {___, p_, q_, ___}, ___List}], _}] := q
OnPoints[p_Integer, {Cycles[{___List, {q_, ___, p_},      ___List}], _}] := q
OnPoints[p_Integer, {Cycles[{___List}], _}]                              := p

OnPoints[p_Integer, s_. * perm_Imag]         := OnPoints[p, perm]  (* 부호 무시 *)
OnPoints[p_Integer, imag:Imag[___, p_, ___]] := imag[[p]]
OnPoints[p_Integer, Imag[___]]               := p

(* Gives the CyclesSigned permutation that converts lst1 into lst2. *)
PermFromTo::diff = "`1` and `2` contain different points."
PermFromTo[lst1:head_[___], lst2:head_[___]] :=
    If [Sort[lst1] =!= Sort[lst2], Message[PermFromTo::diff, lst1, lst2],
    (* else *)                     {FindPermutation[lst1, lst2], 1}]

(* Generates a strong generating set for the group generated by GS of CyclesSigned *)
SchreierSims[gs_GenSet, opts___Rule] :=  (* One possible option is GroupActionBase -> base_List *)
    With[{len = PermMax[gs]},
        With[{chainL = GroupStabilizerChain[gensetToPermGroup[gs, len], opts]},
            With[{base = Select[chainL[[-1,1]], (# <= len)&]},  (* 부호 고려 *)
                StrongGenSet[base, GenSet @@ (toCyclesSigned[#, len]& /@ chainL[[1,-1,1]])]
            ]
        ]
    ]

(* Gives a canonical representative of the double coset S.perm.D,
   where S is generated by GS and D is the group of symmetries of the DummySets. *)
CanonicalPerm::sign = "`1` is not a sign."
Options[CanonicalPerm] = {Verbose -> False}
CanonicalPerm[perm:{_Cycles, 1 | -1}, len_, gs_GenSet, frees_List, sets:{(_DummySet | _RepeatedSet)...}, opts___Rule] := linkCanonicalPerm[perm, len, SchreierSims[gs], frees, sets, opts]
CanonicalPerm[s_. * imag_Imag,        len_, gs_GenSet, frees_List, sets:{(_DummySet | _RepeatedSet)...}, opts___Rule] := (
        If [s^2 =!= 1, Message[CanonicalPerm::sign, s]; Return[$Failed]];

        With[{result = CanonicalPerm[ToCycl[s * imag], len, gs, frees, sets, opts]},
            If [result =!= Null, ToImag[result, len],
            (* else *)           Null]  (* MathLink error in xpermConnect[] *)
        ]
    )

(********************************************)

$mPermDirectory :=
    With[{lst = FileNames["mPerm",
                          StringJoin[#, "/Applications"]& /@ {$UserBaseDirectory,
                                                              $BaseDirectory,
                                                              $InstallationDirectory <> "/AddOns"}]},
        If[lst =!= {}, First[lst], {}]
    ]

xpermConnect[] :=
    If [$xpermCPP =!= True,  (* True if the connection was successful, or False if it failed. *)
        With[{version = System`$Version, dir = StringJoin[$mPermDirectory, "/LibraryResources/"]},
            Module[{result = True},
                Which [
                    StringMatchQ[version, ___ ~~ "Windows" ~~ ___], $xpermExecutable = StringJoin[dir, "xPermCPP64.mswin"],
                    StringMatchQ[version, ___ ~~ "Linux"   ~~ ___], $xpermExecutable = StringJoin[dir, "xPermCPP64.linux"],
                    StringMatchQ[version, ___ ~~ "Mac"     ~~ ___], $xpermExecutable = StringJoin[dir, "xPermCPP64.mac-arm"],
                    True,                                           Print["Unsupported system."]; result = False
                ];

                Check[Install[$xpermExecutable], result = False];
                If [!result, Print["Connection failed."]];
                $xpermCPP = result;
                Return[result]
            ]
        ]
    ]

(* CyclesSigned -> Imag -> Unsigned imag-list *)
toImagList[gs_GenSet, len_] := Flatten @ Apply[List, toImagList[#, len]& /@ gs]
toImagList[perm_, len_]     := toImagListProper[ToImag[perm, len], len]

    (* Imag -> Unsigned imag-list *)
    toImagListProper[s_. * Imag[ns___], len_] := If [s < 0, Join[{ns}, len + {2,1}],
                                                 (* else *) Join[{ns}, len + {1,2}]]

(* Unsigned imag-list -> CyclesSigned *)
fromImagList[{(0)..},    _]          := 0  (* for CanonicalPerm *)
fromImagList[imag_List, len_Integer] := {PermutationCycles @ Drop[imag, -2],
                                         If [OnPoints[len+1, Imag @@ imag] === len+1, 1, -1]}

linkCanonicalPerm[perm_, len_Integer, sgs_, frees_List, sets_, opts___] :=
    With[{vb = Verbose /. {opts} /. Options[CanonicalPerm], callF = mPerm`Private`MLCanonicalPerm},
        If [vb,
            Print["Calling 'MLCanonicalPerm' with the following arguments:"];
            Print["1st: perm = ", toImagList[perm, len]];
            Print["2nd: deg = ", len + 2];
            Print["3rd: {base, GS} = ", List @ sgsList[sgs, len]];
            Print["4th: freeps = ", frees];
            Print["5th: vds, dummies, mQ, vrs, repes = ", List @ translateSet[sets]];
        ];

        If [xpermConnect[] =!= False,
            fromImagList[
                callF[
                    toImagList[perm, len],
                    len + 2,
                    sgsList[sgs, len],
                    frees,
                    translateSet[sets]
                ],
                len
            ],
        (* else *)
            Null  (* MathLink error in xpermConnect[] *)
        ]
    ]

    sgsList[StrongGenSet[base_List, gs_GenSet], len_] := Sequence[takeNext[base, {}, Range[len]],
                                                                  toImagList[gs, len]]

        takeNext[{a_, other___}, {found___}, lst_List] :=
            With[{sublist = Complement[Select[lst, # < a&], {other}]},
                takeNext[{other}, Flatten[{found, sublist, a}], Complement[lst, sublist, {a}]]
            ]
        takeNext[{}, found_, lst_List] := Join[found, lst]

    (* translate the DummySet and RepeatedSet structures into lists of numbers: *)
    translateSet[DummySet[_, dums_, sym_]] := {Flatten[{dums}], sym}
    translateSet[RepeatedSet[lst_]]        := Flatten[{lst}]
    translateSet[sets_List]                :=
        translateSetStructure[{transpose[translateSet /@ Cases[sets, DummySet[_,{__},_]]],
                               translateSet /@ Cases[sets, _RepeatedSet]}]

        translateSetStructure[{{dumSets_, mQ_}, repSets_}] :=
            Sequence[Length /@ dumSets, Flatten[dumSets], mQ, Length /@ repSets, Flatten[repSets]]

        transpose[{}] := {{}, {}}
        transpose[x_] := Transpose[x]

linkMakePermGroup[GS_GenSet, len_Integer] := (
        If [xpermConnect[] =!= False,
            With[{result = mPerm`Private`MLMakePermGroup[toImagList[GS, len], len+2]},
                fromImagList[#, len]& /@ Partition[result, len + 2]
            ],
        (* else *)
            Null  (* MathLink error in xpermConnect[] *)
        ]
    )

(********************************************************************)
End[] (* end the private context *)

EndPackage[] (* end the package context *)
